### ISSUE TITLE
How to generate the Separable kernels?

### ISSUE THREAD

**Issue by wendyWeng** [sniklaus/pytorch-sepconv#11]
Hi, thank you for your idea and codes. But I could not understand the Separable kernel. The kernels mentioned in the paper are 1D,  but in my opinion, the output of the sub-network should be 51x128x128. I am very confused

**Comment by sniklaus** [comment]
Each sub-network does indeed return [51 channels](https://github.com/sniklaus/pytorch-sepconv/blob/9cdabbe592c822586b075c6b7659de995613025e/run.py#L67) as you correctly noted. The height and width depend on the input size, the utilized architecture is fully-convolutional and can thus handle inputs with a (to a certain degree) arbitrary size. Does this clear things up?

**Comment by wendyWeng** [comment]
Thanks for your kindly reply. But I don not  know whether the outputs of 4 subnetworks are 1D kernels or not.

**Comment by sniklaus** [comment]
They are interpreted as 1D kernels, yes.

**Comment by wendyWeng** [comment]
Sorry, I still could not understand how to transfer 51 channels feature maps into 1 D kernel,  and I didn't find the transformation in run.py .

**Comment by sniklaus** [comment]
They are being applied in the [SeparableConvolution](https://github.com/sniklaus/pytorch-sepconv/blob/master/src/SeparableConvolution_kernel.cu) layer.

**Comment by wendyWeng** [comment]
Thank you!!!
