### ISSUE TITLE
Installing on macOS not possible

### ISSUE THREAD

**Issue by claxonberlin** [sniklaus/pytorch-sepconv#12]
Hi

I'm trying to get things to function, but I keep getting errors. I believe this is due to nVidia's cuDNN libraries/primitives not being available for macOS.

Is there a way around this?

Kind regards.

**Comment by sniklaus** [comment]
You could try commenting out [this line](https://github.com/sniklaus/pytorch-sepconv/blob/master/run.py#L16) to disable cuDNN and see whether the errors still occur. I am afraid that I only work with Linux and can thus likely not provide further guidance.

**Comment by claxonberlin** [comment]
The problem is that I had to [install pytorch](https://github.com/pytorch/pytorch#installation) from source. Doing this, I disabled CUDA support because I kept getting build errors due to cuDNN not being available. 

Now when I run `run.py` I get an `AttributeError: 'module' object has no attribute '_cuda_getDevice'`. So I guess I won't be able to run sepconv anytime soon on macOS?

**Comment by sniklaus** [comment]
That sounds more like an issue related to PyTorch, the official [discussion forum](https://discuss.pytorch.org/) might be a better place to seek help in this regard. It seems like people who experience this issue are encouraged to do the inference on the CPU without using CUDA at all. However, the separable convolution layer is unfortunately only implemented in CUDA so far.
