### ISSUE TITLE
Dose the SeparableConvolution layer need backward ?

### ISSUE THREAD

**Issue by wendyWeng** [sniklaus/pytorch-sepconv#13]
Hi! Dose the SeparableConvolution layer need backward ? if need,could you tell me how to define it's backword function

**Comment by meipuru344** [comment]
Hi, I wrote backward code.
Check it out :)
https://github.com/meipuru344/sepconv

**Comment by sniklaus** [comment]
I am closing this for now, there are a few third-party implementations for the gradient computation by now. My apologies that it wasn't able to release one myself, but huge thanks for being interested in my work!
