### ISSUE TITLE
One issue about SeparableConvolution.py

### ISSUE THREAD

**Issue by YaoooLiang** [sniklaus/pytorch-sepconv#14]
Thank you for your great works!
The funtion :SeparableConvolution_cuda_forward(input,vertical,horizontal,output) which can be seen in SeparableConvolution.py. I want to ask  if vertical's 51channels just multiply by each column in 51*51 patches of input and   horizontal's 51channels multiply by each row of patches ,and then add them to 1D new pixels ?
Looking forward to your reply!

**Comment by sniklaus** [comment]
I am afraid that I am not entirely sure what your question is. You can find the implementation of the separable convolution at the link below though, which might clear things up.

https://github.com/sniklaus/pytorch-sepconv/blob/593d284608aea921e554abab7ee4eec843ed1d6f/src/SeparableConvolution_kernel.cu#L40
