### ISSUE TITLE
training data set frame rate

### ISSUE THREAD

**Issue by sdlpkxd** [sniklaus/pytorch-sepconv#15]
Excuse me, what's the frame rate  of videos in your training data set, 60fps ?

**Comment by sniklaus** [comment]
The frame-rate of the videos varies between 24 and 30 frames per second. We must have forgotten to mention this in our paper, my apologies.

**Comment by sdlpkxd** [comment]
Great works, thanks.

**Comment by LINSEVENQI** [comment]
Excuse me , do you have a training set for the article "Video Frame Interpolation via Adaptive Separable Convolution"?Would you like to share it with me if you have one?Thanks!!!!!!
