### ISSUE TITLE
Request of  your train code model.

### ISSUE THREAD

**Issue by ss0415** [sniklaus/pytorch-sepconv#18]
I'm intersted in your work,but there is no how to train the model.If you can offer it,I'll very thank you.

**Comment by meipuru344** [comment]
https://github.com/meipuru344/sepconv
I wrote train code.
You can check it out :)

**Comment by l2009312042** [comment]
@meipuru344  follow your work ,i fix some bug and   write the train code  to train pic 
https://github.com/l2009312042/sepconv

**Comment by sniklaus** [comment]
Thank you for being interested in our work! I am closing this since it is a duplicate of #3 and since there are a few forks, like the one from @meipuru344, who show how to do training with adaptive separable convolutions. This may also be a worthwhile read: https://arxiv.org/abs/1809.07759
