### ISSUE TITLE
Not working on grayscale images

### ISSUE THREAD

**Issue by emrecagin** [sniklaus/pytorch-sepconv#19]
Hi, I used your code in several images and it worked fine. However, when I tried on a gray scale image, I had the following error
`Traceback (most recent call last): 
File "run.py", line 257, in  
tensorInputFirst = torch.FloatTensor(numpy.rollaxis(numpy.asarray(PIL.Image.open(arguments_strFirst))[:,:,::-1], 2, 0).astype(numpy.float32) / 255.0) 
IndexError: too many indices for array`
Is there a way your code works for gray scale images.

**Comment by sniklaus** [comment]
Try changing it to the following, in which `.convert('RGB')` is added.

```
tensorInputFirst = torch.FloatTensor(numpy.array(PIL.Image.open(arguments_strFirst).convert('RGB'))[:, :, ::-1].transpose(2, 0, 1).astype(numpy.float32) / 255.0)
tensorInputSecond = torch.FloatTensor(numpy.array(PIL.Image.open(arguments_strSecond).convert('RGB'))[:, :, ::-1].transpose(2, 0, 1).astype(numpy.float32) / 255.0)
```

**Comment by emrecagin** [comment]
Thank you so much It worked!
