### ISSUE TITLE
Upsample error?

### ISSUE THREAD

**Issue by ericwu09** [sniklaus/pytorch-sepconv#2]
Hi,
I receive this error when I try running the command 'run.py --model lf --first ./images/first.png --second ./images/second.png --out ./result.png':

  File "run.py", line 163, in <module>
    moduleNetwork = Network().cuda()
  File "run.py", line 88, in __init__
    torch.nn.Upsample(scale_factor=2, mode='bilinear'),
AttributeError: 'module' object has no attribute 'Upsample'

Could this have to do with the PyTorch version?

Thanks!

**Comment by sniklaus** [comment]
The `torch.nn.Upsample` layer was introduced in the most recent release of PyTorch. If you are not able or willing to update your PyTorch, you can alternatively use the `torch.nn.UpsamplingBilinear2d` layer instead.
