### ISSUE TITLE
No module named '_ext'

### ISSUE THREAD

**Issue by 9Ginseng** [sniklaus/pytorch-sepconv#20]
Applause to everyone involved in making this, it is amazing.

Anyway this is the first time I'm using python, please be gentle.
When I try to run "run.py" I get this following error:

Traceback (most recent call last):
  File "run.py", line 13, in <module>
    from SeparableConvolution import SeparableConvolution # the custom SeparableConvolution layer
  File "D:\Users\-\Desktop\Sepconv\pytorch-sepconv-master\SeparableConvolution.py", line 3, in <module>
    import _ext.cunnex
ModuleNotFoundError: No module named '_ext'

Not sure what I'm missing, I'm using python 3.6.

**Comment by sniklaus** [comment]
Thank you for being interested in our work. Did you make sure to run `install.bash`?

**Comment by 9Ginseng** [comment]
I did, I ran it again and saw this:
install.bash: line 3: python: command not found
install.bash: line 5: nvcc: command not found
install.bash: line 7: python: command not found

Missed it the first time i guess?
I have python 3.6, CUDA 9.2 and the latest pytorch version, is there anything more i need?

‘network-l1.pytorch’ and ‘network-lf.pytorch’ were already downloaded though.

**Comment by sniklaus** [comment]
It looks like your Python binary is not called `python` and you are probably missing the CUDA toolkit.

**Comment by 9Ginseng** [comment]
Oh... I'm on Windows 10, using bash trough the "Windows subsystem for Linux" feature so I would have to install everything trough the Ubuntu terminal otherwise bash can't communicate with python or CUDA... I'm guessing? I just sort of assumed it would work since it enables the use of bash in cmd.

**Comment by sniklaus** [comment]
Yes, that is an issue, I am afraid that the provided implementation is designed to run on Linux.

**Comment by sniklaus** [comment]
I just updated the code and it now uses CuPy, which might allow you to run it on Windows. I would be happy to hear back from you whether or not this is the case. Thanks!

**Comment by junekyoopark** [comment]
Sorry for waking up a dead thread. I found this work fascinating so wanted to give it a go on Windows. I installed CuPy, but it gives the same error. 

EDIT: I think it is because it is not possible to use CUDA through the Linux bash on Windows as indicated by Robert_Crovella here: **https://devtalk.nvidia.com/default/topic/968367/cuda-setup-and-installation/install-cuda-8-on-ubuntu-bash-windows-10/**

**Comment by sniklaus** [comment]
Have you tried running `python run.py` from within the Anaconda prompt?

**Comment by junekyoopark** [comment]
Yep, ran it in both command prompt and Anaconda prompt. Same results.

EDIT: WSL does not support CUDA yet, which is why this does not work. Will update when CUDA support is added.

**Comment by sniklaus** [comment]
I am sorry to hear that. I unfortunately do not have a Windows configuration to debug this. Please keep us updated in case you are able to make it work!

**Comment by youyingyin** [comment]
> I am sorry to hear that. I unfortunately do not have a Windows configuration to debug this. Please keep us updated in case you are able to make it work!

I noticed the latest code contains backwards function, does it mean that we can train the model?
