### ISSUE TITLE
problem with compilation 

### ISSUE THREAD

**Issue by pczebra** [sniklaus/pytorch-sepconv#24]
I installed in ubuntu16.04.  When I run the` bash install.bash` , i get the following error. 
```
huwenchao@huwenchao-B350GT3:~/cv/pytorch-sepconv-master$ bash install.bashIn file included from /home/huwenchao/anaconda2/lib/python2.7/site-packages/torch/lib/include/THC/THCGeneral.h:5:0,
                 from /home/huwenchao/anaconda2/lib/python2.7/site-packages/torch/lib/include/THC/THC.h:4,
                 from src/SeparableConvolution_kernel.cu:1:
/home/huwenchao/anaconda2/lib/python2.7/site-packages/torch/lib/include/TH/THAllocator.h:6:28: fatal error: ATen/Allocator.h: No such file or directory
 #include <ATen/Allocator.h> ^
compilation terminated.
gcc: error: /home/huwenchao/cv/pytorch-sepconv-master/src/SeparableConvolution_kernel.o: No such file or directory
Traceback (most recent call last):
  File "install.py", line 32, in <module>
    objectExtension.build()
  File "/home/huwenchao/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/huwenchao/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/huwenchao/anaconda2/lib/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/huwenchao/anaconda2/lib/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/huwenchao/anaconda2/lib/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/huwenchao/anaconda2/lib/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1
```
I am a novice to this,please help me.

**Comment by sniklaus** [comment]
The issue is `ATen/Allocator.h: No such file or directory` which is part of PyTorch. I am afraid that I cannot provide support for PyTorch, my guess is you installed it in an unusual way. I would thus recommend you try re-installing PyTorch using `conda install ...`.

**Comment by pczebra** [comment]
thanks for your help ,i use  `pytorch 0.4.0` instead of `pytorch 0.4.1-py27_cuda9.0.176_cudnn7.1.2_1` , then everything is ok ,i dont know why but it works

**Comment by sniklaus** [comment]
I am happy to hear that and thank you for bringing it to my attention. I can confirm that it does not compile with the newest version of PyTorch and I will fix this as soon as I get around to do it. Thanks!

**Comment by sniklaus** [comment]
I just updated the code and it now uses CuPy, which makes it possible to use PyTorch `0.4.1` without any issues. Again, thank you for bringing this to my attention!

**Comment by youyingyin** [comment]
> I just updated the code and it now uses CuPy, which makes it possible to use PyTorch `0.4.1` without any issues. Again, thank you for bringing this to my attention!

I noticed the latest code contains backward function, does it means that we can train the model?

**Comment by maximelianos** [comment]
> thanks for your help ,i use `pytorch 0.4.0` instead of `pytorch 0.4.1-py27_cuda9.0.176_cudnn7.1.2_1` , then everything is ok ,i dont know why but it works

Downgrading torch 0.4.1 to 0.4.0 also solved the include error for me. Thanks!
