### ISSUE TITLE
error in run.py 

### ISSUE THREAD

**Issue by SanSLee** [sniklaus/pytorch-sepconv#26]
Traceback (most recent call last):
  File "run.py", line 172, in <module>
    moduleNetwork = Network().cuda().eval()
  File "run.py", line 124, in __init__
    self.load_state_dict(torch.load('network-' + arguments_strModel + '.pytorch'))
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, '<'.

When I run the file run.py, the error above  occurred. Hope someone can help me.

**Comment by sniklaus** [comment]
It could be that the state dict got corrupted. The md5 hashes of them should be as follows.

```
ca2cea416fb99108bb08a8bfd31993cb  network-l1.pytorch
9121087a0550b77ebd6ae4100e4398a3  network-lf.pytorch
```

Can you check and see whether the md5 hashes of yours matches these?

**Comment by UESTCshiny** [comment]
Thanks! These two files have the same md5 value. That may be the problem and and how can I solve it?

**Comment by SanSLee** [comment]
Thanks! These two files have the same md5 value. That may be the problem and how can I solve it?

**Comment by sniklaus** [comment]
I am afraid that I am confused. You said that your files have the same md5 hash and note that this could be the underlying problem. Did you mean to say that your files have different md5 hashes?

Should they differ then I would recommend downloading the models again. Should they match then you might want to consider the following discussion: https://github.com/CSAILVision/places365/issues/25#issuecomment-333871990

**Comment by UESTCshiny** [comment]
> I am afraid that I am confused. You said that your files have the same md5 hash and note that this could be the underlying problem. Did you mean to say that your files have different md5 hashes?
> 
> Should they differ then I would recommend downloading the models again. Should they match then you might want to consider the following discussion: [CSAILVision/places365#25 (comment)](https://github.com/CSAILVision/places365/issues/25#issuecomment-333871990)

The md5 hashes of network-lf and network-l1 are as follows
image
Thanks again! I download the models again but the md5 hashes are the same as before. They don't match the your values.

**Comment by sniklaus** [comment]
Are you behind a firewall that alters your downloads by chance?

**Comment by SanSLee** [comment]
The problem is that the model files were downloaded incompletely before. I download them again in another way. Thanks for your help and your wonderful work!
