### ISSUE TITLE
How to setup on windows?

### ISSUE THREAD

**Issue by deama** [sniklaus/pytorch-sepconv#29]
Hello,

So first off, this is concerning specifically the video supported extension found here:
https://github.com/dagf2101/pytorch-sepconv

There do not seem to be any instructions on how to install it on windows and the lack of information for what libraries are used does not help either. I already have pytorch setup, but I do not know how to proceed further, could you help me? When I open up the install.bash file it mentions nvcc, do I just install that? But then it has these various configuration parameters...
I also have anaconda installed (similiar to pip).

**Comment by sniklaus** [comment]
I am afraid that I am unable to provide support for third-party forks of this repository. My apologies.

**Comment by deama** [comment]
Could you help me with setting up your one?

**Comment by deama** [comment]
Could you help me with your one then?
I am getting an error when I try to run run.py:
"ModuleNotFoundError: no module named torch.utils.serialization"

**Comment by deama** [comment]
Could you help me with your one then?
I am getting an error when I try to run run.py:
"ModuleNotFoundError: no module named torch.utils.serialization"
