### ISSUE TITLE
"ModuleNotFoundError: no module named torch.utils.serialization"

### ISSUE THREAD

**Issue by deama** [sniklaus/pytorch-sepconv#30]
Hello,

I've tried to run the run.py file with my anaconda pytorch setup, however it gives me the:
"ModuleNotFoundError: no module named torch.utils.serialization"
error. I can't seem to find any information on how to fix this or really where that serialization package is from.

**Comment by deama** [comment]
Sorry, I can't seem to edit my posts so I'll post an update.
It seems that renaming "torch.utils.serialization" to "torch.serialization" fixes the no module error, however it gives me another error that is the same as if I removed the "import torch.utils.serialization line":
AttributeError: module 'sepconv' has no attribute 'FunctionSepconv'
I assume this is probably caused by it not importing the "torch.utils.serialization" module correct?

**Comment by deama** [comment]
After tinckering with it some more, I downgraded my pytorch version and managed to make that error disappear. However a new one has come, it is the same one that came up when I removed the "import torch.utils.serialization" line:
AttributeError: module 'sepconv' has no attribute 'FunctionSepconv'

Any ideas?

**Comment by sniklaus** [comment]
I fixed the `ModuleNotFoundError: no module named torch.utils.serialization` error in the newest commit. The `AttributeError` might be an issue with Python, try making sure that you use Python 3.

**Comment by deama** [comment]
I'm using python 3.7, is that why the attribute error is occuring? Maybe python 3.6 would work?

**Comment by deama** [comment]
Ok so I reinstalled anaconda with the pytorch version 0.4.1 and python 3.6, but I'm getting the same AttributeError.

**Comment by sniklaus** [comment]
I am afraid that I do not use Windows and am unable to further investigate this issue, my apologies.

**Comment by CM-BF** [comment]
Actually I faced the same issue on Ubuntu 18.04(python3.6), and Windows10(python3.7).
