### ISSUE TITLE
AttributeError: module 'torch._C' has no attribute '_cuda_getDevice'

### ISSUE THREAD

**Issue by cloudzero-zz** [sniklaus/pytorch-sepconv#32]
AttributeError: module 'torch._C' has no attribute '_cuda_getDevice'

I have cuda, but it's not finding it somehow?

**Comment by sniklaus** [comment]
Looks like it is an [issue with PyTorch](https://github.com/pytorch/pytorch/issues/5286) and I am unfortunately unable to help you troubleshoot your environment. If the linked issue does not have a solution to help you with this error, I would recommend seeking further advice in the [PyTorch forum](http://discuss.pytorch.org/).

**Comment by GordonDongZHAO** [comment]
According to docs, I believe you should be loading your models with

torch.load(file, map_location='cpu')
