### ISSUE TITLE
SyntaxError in run.py

### ISSUE THREAD

**Issue by tsuchim** [sniklaus/pytorch-sepconv#36]
The latest run.py doesn't work on Python 3.7.4.
Is the run.py written for the other Python version?

Cloned Commit:
commit c455bc8f8df46fd1ad0b2ac9d60e4f64c7257cd1
Date:   Mon Aug 12 19:04:13 2019 -0700

Error:
$ python ./run.py
  File "./run.py", line 199
    for intFrame, numpyFrame in enumerate(numpyFrame[:, :, ::-1] for numpyFrame in moviepy.editor.VideoFileClip(filename=arguments_strVideo).iter_frames():

^ (←indicate to ":" at the end of line)
SyntaxError: invalid syntax

Python Version:
Python 3.7.4 (default, Aug 24 2019, 12:36:21)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux

**Comment by sniklaus** [comment]
Thank you for bringing this to my attention and for the detailed description of your environment! I just fixed this issue in 76bc80f, please don't hesitate to reach out to me again in case you are still having any issues. Thanks!
