### ISSUE TITLE
see_you_again_540.mp4

### ISSUE THREAD

**Issue by zhhezhhe** [sniklaus/pytorch-sepconv#37]
Could you provide the video "project/videos/see_you_again_540.mp4"?

**Comment by sniklaus** [comment]
This repository does not contain this path / file. A search on Github shows that the following projects do.

https://github.com/martkartasev/sepconv
https://github.com/olyuninv/mv_net

As such, you will have to reach to them instead. My best guess is that it is this video that you can download from Youtube: https://www.youtube.com/watch?v=RgKAFK5djSk
