### ISSUE TITLE
vaule of interpolation

### ISSUE THREAD

**Issue by Jerchongkong** [sniklaus/pytorch-sepconv#38]
I have noticed that when interpolating an image or video does it x2, is there a way to increase the amount of interpolation for example x4 or x8?

**Comment by sniklaus** [comment]
The video interpolation actually interpolates three intermediate frames, not just a single one.

https://github.com/sniklaus/pytorch-sepconv/blob/76bc80fa9584801e6f0a32996253e317a46c1370/run.py#L203-L205

You could further extend this and have it interpolate seven frames at a time. You can likewise adjust the behavior when given two images to continue the interpolation in a recursive manner.
