### ISSUE TITLE
Make it work with pytorch installations from wheel packages

### ISSUE THREAD

**Issue by Qub3k** [sniklaus/pytorch-sepconv#39]
I have decided to spare myself the "pleasure" of building pytorch from source (necessary if you want to have the CUDA support on Linux). Thus, I have used the ready made wheel package (see [here](https://download.pytorch.org/whl/torch_stable.html)). The problem is that the pytorch it installs has the following version string: `1.3.1+cu100`. This makes your code complain when checking the pytorch version (I link the appropriate line from run.py).

https://github.com/sniklaus/pytorch-sepconv/blob/76bc80fa9584801e6f0a32996253e317a46c1370/run.py#L24

By substituting your code with the one below, the installation with wheel package passes the assertion (and the same is true for standard pytorch installations):
`assert(int(str('').join(torch.__version__.split('.')[0:3]).split('+')[0]) >= 41)`

I am sorry for not making this a pull request.

**Comment by sniklaus** [comment]
Thank you for sharing this! I will update it accordingly on my local repository and it will be pushed to Github the next time I sync my projects. Thanks!
