### ISSUE TITLE
test 

### ISSUE THREAD

**Issue by LINSEVENQI** [sniklaus/pytorch-sepconv#42]
Hello! Can I test videos of any resolution based on your network? Because I tested the 4K video display is not very good。
[out_0.zip](https://github.com/sniklaus/sepconv-slomo/files/3977128/out_0.zip)

**Comment by sniklaus** [comment]
You must have commented out these two lines to be able to process videos at a 4K resolution.

https://github.com/sniklaus/sepconv-slomo/blob/6460c47b236df49737b50507e59b4a10a6f17a2d/run.py#L145-L146

The per-pixel motion for 4K video footage is fairly large. In fact, the per-pixel motion in most 4K footage is probably larger than what can be addressed with the size of the adaptive kernels of the provided model.
