### ISSUE TITLE
Flow calculation

### ISSUE THREAD

**Issue by repers** [sniklaus/pytorch-sepconv#45]
Hi, according to your paper, PWC-Net is used for flow calculation, I have tried to find where exactly this is used in the run.py file, however, I can't seem to find it. Can you tell me where this is used?
Thanks

**Comment by sniklaus** [comment]
This repository provides a reference implementation for the paper "Video Frame Interpolation via Adaptive Separable Convolution": https://arxiv.org/abs/1708.01692

I am afraid that PWC-Net did not exists at the time of publication of this paper, it seems like you are referring to a different paper?

**Comment by repers** [comment]
Hi, thanks for your response, I think I confused it with your context aware synthesis paper, do you have the code published for that as I can't seem to find it?
Thanks

**Comment by sniklaus** [comment]
Please see #10 to track that status of the context aware synthesis code, I am afraid that I do not have any updates on this matter yet. My apologies but thank you for being interested in it!
