### ISSUE TITLE
Assertion Error in Video Frame interpolation

### ISSUE THREAD

**Issue by tianchengdw** [sniklaus/pytorch-sepconv#50]
Hi, Mr. Niklaus!

Thank you for your great work! When I use your code to interpolate my own video(1280*720, 30FPS,40s), an error occurs as shown in Figure. But I successfully generate the output reslut of car-turn.mp4.

 I really appreciate it if anyone can help me .

Thanks in advance!
![Assertion Error](https://user-images.githubusercontent.com/48008841/89862206-061ae200-dbda-11ea-8ba9-b45c705424c7.png)

**Comment by sniklaus** [comment]
The code where this error is raised is as follows.

```
assert(intWidth <= 1280) # while our approach works with larger images, we do not recommend it unless you are aware of the implications
assert(intHeight <= 720) # while our approach works with larger images, we do not recommend it unless you are aware of the implications
```

Have you tried commenting these two lines out?
