### ISSUE TITLE
load_state_dict_from_url() got an unexpected keyword argument 'file_name'

### ISSUE THREAD

**Issue by SDarknessZX** [sniklaus/pytorch-sepconv#54]
can you how to deal with this problem？
thank you very much！
![1616767514(1)](https://user-images.githubusercontent.com/77833411/112643912-d2967a80-8e7f-11eb-89d5-6f45b36d2fea.png)

**Comment by sniklaus** [comment]
The `file_name` got added to `load_state_dict_from_url` in PyTorch 1.6.0, so you can just upgrade your PyTorch to 1.6.0 or newer and then you should be good to go. :+1:
