### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'clip'

### ISSUE THREAD

**Issue by Deerzh** [sniklaus/pytorch-sepconv#56]
when I run this command: python run.py --model lf --one ./images/one.png --two ./images/two.png --out ./out.png, it occured error.
Can you help me fix this issue.

Traceback (most recent call last):
  File "run.py", line 185, in <module>
    PIL.Image.fromarray((tenOutput.clip(0.0, 1.0).numpy().transpose(1, 2, 0)[:, :, ::-1] * 255.0).astype(numpy.uint8)).save(arguments_strOut)
AttributeError: 'Tensor' object has no attribute 'clip'

**Comment by sniklaus** [comment]
Thank you for your interest in our work! Looks like you are using an old version of PyTorch, so either make sure you are using at least version 1.7.0 or alternatively rename "clip" to "clamp".

**Comment by Deerzh** [comment]
Thank you for your suggestion,it's very helpful to me!

**Comment by Deerzh** [comment]
> Thank you for your interest in our work! Looks like you are using an old version of PyTorch, so either make sure you are using at least version 1.7.0 or alternatively rename "clip" to "clamp".

Thank you for your suggestion,it's very helpful to me!
