### ISSUE TITLE
Request of training dataset

### ISSUE THREAD

**Issue by queenieliaw810910** [sniklaus/pytorch-sepconv#6]
@sniklaus 
Thanks for your sharing! The work is quite amazing!
Could you please offer the training dataset? 

Thanks a lot!

**Comment by SpaceMonkeyForever** [comment]
isn't this resolved now? There is a script to download the pre-trained network

**Comment by sniklaus** [comment]
The pre-trained network has always been available, I have not yet found the time and energy to publish the training dataset though. One could give the dataset from [Video Enhancement with Task-Oriented Flow](http://data.csail.mit.edu/tofu/) a try, they have already published it a while ago. I have not trained SepConv myself with their dataset yet, but I am sure it will do sufficiently well.
