### ISSUE TITLE
RuntimeError: tried to construct a tensor from a nested float sequence, but found an item of type numpy.float32

### ISSUE THREAD

**Issue by alex47** [sniklaus/pytorch-sepconv#7]
I am using Ubuntu 17.04 with an Nvidia GTX 980 and CUDA 9
When I try to run the run.py script I get the following error:

```
alex@alex-desktop:~/pytorch-sepconv$ python run.py --model lf --first ./images/first.png --second ./images/second.png --out ./result.png
Traceback (most recent call last):
  File "run.py", line 167, in <module>
    tensorInputFirst = torch.FloatTensor(numpy.rollaxis(numpy.asarray(PIL.Image.open(arguments_strFirst))[:,:,::-1], 2, 0).astype(numpy.float32) / 255.0)
RuntimeError: tried to construct a tensor from a nested float sequence, but found an item of type numpy.float32 at index (0, 0, 0)
```

**Comment by sniklaus** [comment]
I am afraid that I currently am still using Ubuntu 14.04 with CUDA 8 and am unable to reproduce this error. I will get back to this issue once I made the transition over to CUDA 9, in the meantime, you might be able to try one of the suggestions from here: https://github.com/facebookresearch/InferSent/issues/2

**Comment by sniklaus** [comment]
I switched to Ubuntu 16.04 with CUDA 9 and am still to able to reproduce this error. Does it still happen or did an update of one of the dependencies fix the problem by now?

**Comment by alex47** [comment]
thanks for the investigation @sniklaus
I did a fresh install of Ubuntu 16.04 and CUDA 9 and everything works perfectly now
the issue is gone :)

**Comment by sniklaus** [comment]
I am happy to hear that, thank you for the update!
