### ISSUE TITLE
bash install.bash failed

### ISSUE THREAD

**Issue by IOchair** [sniklaus/pytorch-sepconv#8]
I am using Windows 10 with an Nvidia GTX 1060 and CUDA 8.
install.bash failed
`SeparableConvolution_cuda.obj : error LNK2001: unresolved external symbol state
SeparableConvolution_kernel.o : error LNK2001: unresolved external symbol cudaGetLastError
SeparableConvolution_kernel.o : error LNK2001: unresolved external symbol cudaConfigureCall
SeparableConvolution_kernel.o : error LNK2001: unresolved external symbol cudaSetupArgument
SeparableConvolution_kernel.o : error LNK2001: unresolved external symbol cudaLaunch
SeparableConvolution_kernel.o : error LNK2001: unresolved external symbol __imp_THLog1p
SeparableConvolution_kernel.o : error LNK2001: unresolved external symbol __imp_THCState_getCurrentStream
SeparableConvolution_kernel.o : error LNK2001: unresolved external symbol __imp___THCudaCheck
SeparableConvolution_kernel.o : error LNK2001: unresolved external symbol __imp_THCudaTensor_data
SeparableConvolution_kernel.o : error LNK2001: unresolved external symbol __imp_THCudaTensor_nElement
SeparableConvolution_kernel.o : error LNK2001: unresolved external symbol __cudaRegisterFatBinary
SeparableConvolution_kernel.o : error LNK2001: unresolved external symbol __cudaUnregisterFatBinary
SeparableConvolution_kernel.o : error LNK2001: unresolved external symbol __cudaRegisterFunction`
Do I do anything wrong or It's not even possible to make it working on windows?

**Comment by sniklaus** [comment]
I am afraid that I am unable to provide support for Windows, my apologies.
